<script>
  import clsx from "clsx";
  export let stitched_points;
</script>

<main>
  {#each stitched_points as { classification, simplified, text }, i}
    <div>
      <div class="simplified">
        <div class={clsx(classification, "point")}>{text}</div>
        <div class={clsx(simplified === "" && "hide")}>
          <div class="simplified-text">{simplified}</div>
          <div class={clsx("border-label")}>
            Simplified Text <span
              class="explainer"
              title="This is a simplified version of the verbatim point, generated by masking out difficult words and replacing them with predictions from a legal language model."
              >?</span
            >
          </div>
        </div>
      </div>
    </div>
  {/each}
</main>

<style>
  .point {
    text-align: left;
    list-style-type: none;
    padding: 10px;
    margin: 0 0 4px 0;
    background: #ffcccc;
    border: 1px solid;
    border-radius: 5px;
  }

  .hide {
    display: none;
  }

  .simplified {
    text-align: left;
    background: #eee;
    border: 1px solid #ccc;
    border-radius: 5px;
    padding: 0 0 5px 0;
    position: relative;
    margin: 10px;
  }

  .explainer {
    text-decoration: underline;
    text-decoration-style: dotted;
    cursor: help;
  }

  .simplified-text {
    padding: 5px 10px;
    font-size: 0.9em;
  }

  .border-label {
    text-align: right;
    padding: 0px 10px 5px 10px;
    font-size: 0.7em;
  }

  .blocker {
    background: #ffaaaa;
    border-color: #ff7777;
  }
  .bad {
    background: #ffff77;
    border-color: #aaaa55;
  }
  .neutral {
    background: #cccccc;
    border-color: #aaaaaa;
  }
  .good {
    background: #7e7;
    border-color: #2a2;
  }
</style>
